language: go

go:
 - 1.4
 - tip

env:
    - GIMME_OS=linux GIMME_ARCH=amd64
    - GIMME_OS=darwin GIMME_ARCH=amd64
    - GIMME_OS=linux GIMME_ARCH=arm GOARM=7

install:
    - go get -d -v ./...

script:
    - go build -v ./...


